<a href="https://colab.research.google.com/github/Shreyas3108/LLM_Learning/blob/main/Transformer_Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from transformers import pipeline

## Doing Sentiment Analysis

In [5]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


In [9]:
classifier("Neutral")

[{'label': 'NEGATIVE', 'score': 0.9992249011993408}]

In [10]:
classifier = pipeline("zero-shot-classification")
classifier(
    "This is a course about the Transformers library",
    candidate_labels=["education", "politics", "business"],
)

No model was supplied, defaulted to facebook/bart-large-mnli and revision c626438 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


{'sequence': 'This is a course about the Transformers library',
 'labels': ['education', 'business', 'politics'],
 'scores': [0.8445994257926941, 0.11197380721569061, 0.04342673346400261]}

In [14]:
from transformers import pipeline

generator = pipeline("text-generation", model="distilgpt2")
generator(
    "I am going to buy ",
    max_length=30,
    num_return_sequences=2,
)

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'I am going to buy ices, some paper, some paper."'},
 {'generated_text': 'I am going to buy ____ this way?”'}]

In [12]:
from transformers import pipeline

unmasker = pipeline("fill-mask")
unmasker("This notebook will teach you all about <mask> .", top_k=2)

No model was supplied, defaulted to distilbert/distilroberta-base and revision ec58a5b (https://huggingface.co/distilbert/distilroberta-base).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Some weights of the model checkpoint at distilbert/distilroberta-base were not used when initializing RobertaForMaskedLM: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


[{'score': 0.016911868005990982,
  'token': 25776,
  'token_str': ' coding',
  'sequence': 'This notebook will teach you all about coding.'},
 {'score': 0.016769587993621826,
  'token': 38592,
  'token_str': ' Haskell',
  'sequence': 'This notebook will teach you all about Haskell.'}]

## Tokenizer

In [16]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")
classifier(
    [
        "I am learning from HuggingFace.",
        "I hate this so much!",
    ]
)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


[{'label': 'POSITIVE', 'score': 0.9960522055625916},
 {'label': 'NEGATIVE', 'score': 0.9994558691978455}]

In [17]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [18]:
inp = [
        "I am learning from HuggingFace.",
        "I hate this so much!",
    ]

In [19]:
inputs = tokenizer(inp , padding = True , truncation = True , return_tensors = "pt")

In [20]:
inputs

{'input_ids': tensor([[  101,  1045,  2572,  4083,  2013, 17662, 12172,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0]])}

## Going through the model

In [21]:
from transformers import AutoModel

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModel.from_pretrained(checkpoint)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

In [25]:
model.transformer

Transformer(
  (layer): ModuleList(
    (0-5): 6 x TransformerBlock(
      (attention): MultiHeadSelfAttention(
        (dropout): Dropout(p=0.1, inplace=False)
        (q_lin): Linear(in_features=768, out_features=768, bias=True)
        (k_lin): Linear(in_features=768, out_features=768, bias=True)
        (v_lin): Linear(in_features=768, out_features=768, bias=True)
        (out_lin): Linear(in_features=768, out_features=768, bias=True)
      )
      (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (ffn): FFN(
        (dropout): Dropout(p=0.1, inplace=False)
        (lin1): Linear(in_features=768, out_features=3072, bias=True)
        (lin2): Linear(in_features=3072, out_features=768, bias=True)
        (activation): GELUActivation()
      )
      (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    )
  )
)

In [26]:
outputs = model(**inputs)

In [27]:
print(outputs.last_hidden_state.shape)

torch.Size([2, 9, 768])


In [34]:
import torch

predictions = torch.nn.functional.softmax(outputs['last_hidden_state'], dim=-1)
print(predictions)

tensor([[[0.0010, 0.0013, 0.0017,  ..., 0.0014, 0.0021, 0.0014],
         [0.0015, 0.0017, 0.0022,  ..., 0.0016, 0.0019, 0.0012],
         [0.0013, 0.0018, 0.0023,  ..., 0.0015, 0.0018, 0.0012],
         ...,
         [0.0010, 0.0015, 0.0021,  ..., 0.0016, 0.0017, 0.0014],
         [0.0009, 0.0011, 0.0019,  ..., 0.0020, 0.0020, 0.0009],
         [0.0025, 0.0017, 0.0015,  ..., 0.0023, 0.0012, 0.0008]],

        [[0.0008, 0.0023, 0.0010,  ..., 0.0010, 0.0004, 0.0011],
         [0.0009, 0.0028, 0.0010,  ..., 0.0008, 0.0006, 0.0014],
         [0.0009, 0.0027, 0.0010,  ..., 0.0009, 0.0005, 0.0012],
         ...,
         [0.0011, 0.0027, 0.0009,  ..., 0.0009, 0.0004, 0.0010],
         [0.0012, 0.0017, 0.0010,  ..., 0.0008, 0.0005, 0.0010],
         [0.0009, 0.0030, 0.0012,  ..., 0.0010, 0.0005, 0.0010]]],
       grad_fn=<SoftmaxBackward0>)


In [35]:
from transformers import AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**inputs)

In [36]:
print(outputs.logits.shape)

torch.Size([2, 2])


In [37]:
print(outputs.logits)

tensor([[-2.7703,  2.7603],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)


In [38]:
predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(predictions)

tensor([[3.9478e-03, 9.9605e-01],
        [9.9946e-01, 5.4418e-04]], grad_fn=<SoftmaxBackward0>)


In [39]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [47]:
import pandas as pd
import numpy as np
pd.DataFrame(predictions.detach().numpy() , columns = ['negative' , 'postive'] , index = [0,1])

negative   postive
0  0.003948  0.996052
1  0.999456  0.000544

## Creating a transformer

In [48]:
from transformers import BertConfig, BertModel

In [49]:
config = BertConfig()
model = BertModel(config)

In [50]:
config

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.44.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

In [51]:
sequences = ["Hello!", "Cool.", "Nice!"]

In [56]:
inputs_seq = tokenizer(sequences , return_tensors = "pt")

In [63]:
inputs_seq.keys()

dict_keys(['input_ids', 'attention_mask'])

In [64]:
inputs_seq['input_ids']

tensor([[ 101, 7592,  999,  102],
        [ 101, 4658, 1012,  102],
        [ 101, 3835,  999,  102]])

In [65]:
model_inputs = torch.tensor(inputs_seq['input_ids'])

<ipython-input-65-caf3ddde1c11>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  model_inputs = torch.tensor(inputs_seq['input_ids'])


In [66]:
output = model(model_inputs)

In [67]:
m = tokenizer.tokenize("Hello! I am someone")

In [69]:
m1 = tokenizer.convert_tokens_to_ids(m)

In [70]:
tokenizer.decode(m1)

'hello! i am someone'

In [71]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)

input_ids = torch.tensor([ids])
print("Input IDs:", input_ids)

output = model(input_ids)
print("Logits:", output.logits)

Input IDs: tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012]])
Logits: tensor([[-2.7276,  2.8789]], grad_fn=<AddmmBackward0>)


/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
